# Usar la imagen base de Golang
FROM golang:1.17

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al directorio de trabajo
COPY . .

# Compilar la aplicación
RUN go build -o Main

# Especificar el comando para ejecutar la aplicación
CMD ["./Main"]
