version: '3'
services:
  base:
    image: "mysql"
    container_name: 'Base_MYSQL'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    image: "api_tarea3"
    container_name: 'Backend_Go'
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: Base_MYSQL
      DB_PORT: 3306
      DB_NAME: prueba
    ports:
      - "8000:8000"
  frontend:
    image: "frontend_tarea3"
    container_name: 'frontend_react'
    ports:
      - "3000:3000"
volumes:
  base_mysql: 